const AudioContext = window.AudioContext;
export const context = new AudioContext();

export const NOTES = {
  C3: 130.81,
  Db3: 138.59,
  D3: 146.83,
  Eb3: 155.56,
  E3: 164.81,
  F3: 174.61,
  Gb3: 185.0,
  G3: 196.0,
  Ab3: 207.65,
  A3: 220.0,
  Bb3: 233.08,
  B3: 246.94,
  C4: 261.63,
  Db4: 277.18,
  D4: 293.66,
  Eb4: 311.13,
  E4: 329.63,
  F4: 349.23,
  Gb4: 369.99,
  G4: 392.0,
  Ab4: 415.3,
  A4: 440,
  Bb4: 466.16,
  B4: 493.88,
  C5: 523.25,
  Db5: 554.37,
  D5: 587.33,
  Eb5: 622.25,
  E5: 659.25,
};

export const BLACK_KEYS = [
  { keyName: '2', code: 'Digit2', note: NOTES.Db3, isBlack: true },
  { keyName: '3', code: 'Digit3', note: NOTES.Eb3, isBlack: true },
  { keyName: '5', code: 'Digit5', note: NOTES.Gb3, isBlack: true },
  { keyName: '6', code: 'Digit6', note: NOTES.Ab3, isBlack: true },
  { keyName: '7', code: 'Digit7', note: NOTES.Bb3, isBlack: true },
  { keyName: '9', code: 'Digit9', note: NOTES.Db4, isBlack: true },
  { keyName: '0', code: 'Digit0', note: NOTES.Eb4, isBlack: true },
  { keyName: 'S', code: 'KeyS', note: NOTES.Gb4, isBlack: true },
  { keyName: 'D', code: 'KeyD', note: NOTES.Ab4, isBlack: true },
  { keyName: 'F', code: 'KeyF', note: NOTES.Bb4, isBlack: true },
  { keyName: 'H', code: 'KeyH', note: NOTES.Db5, isBlack: true },
  { keyName: 'J', code: 'KeyJ', note: NOTES.Eb5, isBlack: true },
];

export const WHITE_KEYS = [
  { keyName: 'Q', code: 'KeyQ', note: NOTES.C3, isBlack: false },
  { keyName: 'W', code: 'KeyW', note: NOTES.D3, isBlack: false },
  { keyName: 'E', code: 'KeyE', note: NOTES.E3, isBlack: false },
  { keyName: 'R', code: 'KeyR', note: NOTES.F3, isBlack: false },
  { keyName: 'T', code: 'KeyT', note: NOTES.G3, isBlack: false },
  { keyName: 'Y', code: 'KeyY', note: NOTES.A3, isBlack: false },
  { keyName: 'U', code: 'KeyU', note: NOTES.B3, isBlack: false },
  { keyName: 'I', code: 'KeyI', note: NOTES.C4, isBlack: false },
  { keyName: 'O', code: 'KeyO', note: NOTES.D4, isBlack: false },
  { keyName: 'P', code: 'KeyP', note: NOTES.E4, isBlack: false },
  { keyName: 'Z', code: 'KeyZ', note: NOTES.F4, isBlack: false },
  { keyName: 'X', code: 'KeyX', note: NOTES.G4, isBlack: false },
  { keyName: 'C', code: 'KeyC', note: NOTES.A4, isBlack: false },
  { keyName: 'V', code: 'KeyV', note: NOTES.B4, isBlack: false },
  { keyName: 'B', code: 'KeyB', note: NOTES.C5, isBlack: false },
  { keyName: 'N', code: 'KeyN', note: NOTES.D5, isBlack: false },
  { keyName: 'M', code: 'KeyM', note: NOTES.E5, isBlack: false },
];

export const KEYS = [
  { keyName: 'Q', code: 'KeyQ', note: NOTES.C3, isBlack: false },
  { keyName: '2', code: 'Digit2', note: NOTES.Db3, isBlack: true },
  { keyName: 'W', code: 'KeyW', note: NOTES.D3, isBlack: false },
  { keyName: '3', code: 'Digit3', note: NOTES.Eb3, isBlack: true },
  { keyName: 'E', code: 'KeyE', note: NOTES.E3, isBlack: false },
  { keyName: 'R', code: 'KeyR', note: NOTES.F3, isBlack: false },
  { keyName: '5', code: 'Digit5', note: NOTES.Gb3, isBlack: true },
  { keyName: 'T', code: 'KeyT', note: NOTES.G3, isBlack: false },
  { keyName: '6', code: 'Digit6', note: NOTES.Ab3, isBlack: true },
  { keyName: 'Y', code: 'KeyY', note: NOTES.A3, isBlack: false },
  { keyName: '7', code: 'Digit7', note: NOTES.Bb3, isBlack: true },
  { keyName: 'U', code: 'KeyU', note: NOTES.B3, isBlack: false },
  { keyName: 'I', code: 'KeyI', note: NOTES.C4, isBlack: false },
  { keyName: '9', code: 'Digit9', note: NOTES.Db4, isBlack: true },
  { keyName: 'O', code: 'KeyO', note: NOTES.D4, isBlack: false },
  { keyName: '0', code: 'Digit0', note: NOTES.Eb4, isBlack: true },
  { keyName: 'P', code: 'KeyP', note: NOTES.E4, isBlack: false },
  { keyName: 'Z', code: 'KeyZ', note: NOTES.F4, isBlack: false },
  { keyName: 'S', code: 'KeyS', note: NOTES.Gb4, isBlack: true },
  { keyName: 'X', code: 'KeyX', note: NOTES.G4, isBlack: false },
  { keyName: 'D', code: 'KeyD', note: NOTES.Ab4, isBlack: true },
  { keyName: 'C', code: 'KeyC', note: NOTES.A4, isBlack: false },
  { keyName: 'F', code: 'KeyF', note: NOTES.Bb4, isBlack: true },
  { keyName: 'V', code: 'KeyV', note: NOTES.B4, isBlack: false },
  { keyName: 'B', code: 'KeyB', note: NOTES.C5, isBlack: false },
  { keyName: 'H', code: 'KeyH', note: NOTES.Db5, isBlack: true },
  { keyName: 'N', code: 'KeyN', note: NOTES.D5, isBlack: false },
  { keyName: 'J', code: 'KeyJ', note: NOTES.Eb5, isBlack: true },
  { keyName: 'M', code: 'KeyM', note: NOTES.E5, isBlack: false },
];

export const pressedNotes = new Map<string, OscillatorNode>();
